### ISSUE TITLE
Does thing

### ISSUE THREAD

**Issue by supersaiyansubtlety** [ssaamm/greasemonkey-scripts#1]
still see ads in search results

**Comment by ssaamm** [comment]
Thanks for the heads up. Should be fixed as of 4de693b. Let me know if you have any problems!

**Comment by supersaiyansubtlety** [comment]
Should this update be applied through tampermonkey? I just tried and the version number stayed the same and ads still aren't hidden. Is there another way to update the script?

**Comment by ssaamm** [comment]
Woops, I didn't even think to test it in Tampermonkey. One thing you could do would be to uninstall the userscript and then install it again (you can [click this link to install](https://github.com/ssaamm/greasemonkey-scripts/raw/master/Etsy_Ad_Remover.user.js)).

**Comment by supersaiyansubtlety** [comment]
Ah, now it’s working, thanks!
